version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  database:
    ports:
      - "5432:5432"
    image: "postgres"
    env_file:
      - .database.env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
